<?php
/**
 * Animate - Adding animation functionality to blocks
 *
 * @package     animate
 * @author      Udit Rawat <eklavyarwt@gmail.com>
 * @license     GPL-2.0+
 * @link        http://sarovarcreative.com/
 * @copyright   SarovarCreative
 * Date:        15/04/2020
 * Time:        07:39 AM
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\block\Entity\Block;
use Drupal\Component\Utility\Html;
use Drupal\block\BlockInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * @param \Drupal\block\BlockInterface $entity
 */
function animate_block_presave(BlockInterface $entity)
{
  if (empty($entity->getThirdPartySetting('animate', 'data_animation'))) {
    $entity->unsetThirdPartySetting('animate', 'data_animation');
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function animate_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  if (\Drupal::currentUser()->hasPermission('administer animate')) {

    /** @var \Drupal\block\BlockInterface $block */
    $block = $form_state->getFormObject()->getEntity();

    // This will automatically be saved in the third party settings.
    $form['third_party_settings']['#tree'] = TRUE;
    // Animation classes
    $anim_classes = \Drupal::service('animate')->getAnimationClasses();
    // Form element for entrance animation
    $form['third_party_settings']['animate']['data_animation'] = [
      '#type' => 'select',
      '#title' => t('Choose Animation'),
      '#description' => t('Add entrance animation to this block.'),
      '#default_value' => $block->getThirdPartySetting('animate', 'data_animation'),
      '#options' => $anim_classes
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param $variables
 */
function animate_preprocess_block(&$variables)
{
  // Blocks coming from page manager widget does not have id.
  if (!empty($variables['elements']['#id'])) {
    $block = Block::load($variables['elements']['#id']);
    // Add entrance animation attribute
    if ($block &&
      $class_in = $block->getThirdPartySetting('animate', 'data_animation')
    ) {
      if (!empty($class_in) && $class_in != "none") {
        $variables['attributes']['data-animation'] = Html::cleanCssIdentifier($class_in, []);
        $variables['attributes']['class'][] = 'animated';
      }
    }
    // Add animation library
    if(($class_in && $class_in != "none")){
      $variables['#attached']['library'][] = 'animate/animate';
    }
  }
}

/**
 * Implements template_preprocess_field_group_html_element
 * @param array $variables
 */
function animate_preprocess_field_group_html_element(array &$variables)
{
  if (array_key_exists('element', $variables) &&
    array_key_exists('#objectType', $variables['element']) &&
    $variables['element']['#objectType'] == 'animated_html_element') {
    $variables['collapsible'] = false;
  }
}
