commerce_payment.commerce_payment_gateway.plugin.commerce_payu_india_redirect:
  type: commerce_payment_gateway_configuration
  mapping:
    key:
      type: string
      label: 'PayU Merchant Key'
    salt:
      type: string
      label: 'PayU Merchant Salt'